name: lacework-iac-scan-pr
on:
  pull_request:
  workflow_dispatch:
permissions:
    id-token: write
    contents: read 
    pull-requests: write 
    security-events: write
    actions: read
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
    # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-20.04
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Checkout Code
            uses: actions/checkout@v3
            - name: Create environment variables file
            # Create an environment variable file that would be passed to the IaC docker image. Note that all relevant environment values need to be passed through here.
            run: |
                env | grep "GITHUB_\|LW_\|CI_" > env.list
                echo "LW_ACCOUNT=${{ secrets.LW_ACCOUNT }}" >> env.list
                # echo "LW_SUBACCOUNT=${{ secrets.LW_SUBACCOUNT }}" >> env.list
                echo "LW_API_KEY=${{ secrets.API_KEY }}" >> env.list
                echo "LW_API_SECRET=${{ secrets.API_SECRET_TOKEN }}" >> env.list
                echo "EXIT_FLAG=CRITICAL=1" >> env.list
            - name: Scan the repo for vulnerabilities in IaC
            run: |
                docker run --env-file env.list -v "$(pwd):/app/src"  -w /app/src lacework/codesec:stable lacework iac scan


       # LW_ACCOUNT: ${{ secrets.LW_ACCOUNT }}
#           # LW_SUBACCOUNT: ${{ secrets.LW_SUBACCOUNT }}
#           LW_API_KEY: ${{ secrets.API_KEY }}
#           LW_API_SECRET: ${{ secrets.API_SECRET_TOKEN }}
#         run: |