name: lacework-iac-scan
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Scan the repo for vulnerabilities in IaC
        env:
          LW_ACCOUNT: ${{ secrets.LW_ACCOUNT }}
          LW_API_KEY: ${{ secrets.API_KEY }}
          LW_API_SECRET: ${{ secrets.API_SECRET_TOKEN }}
        run: |
             echo "$LW_API_KEY" |base64
             # Required to pass the GITHUB and Lacework (LW) environment variables to use
             env | grep "GITHUB_\|LW_\|CI_" > env.list
             # Required command based on what you want to scan in the repository
             echo "SCAN_COMMAND=tf-scan" >> env.list
             # Required if you are not mounting the volume on /app
             echo "WORKSPACE=src" >> env.list
             # if we want to fail the step for any critical failed findings (violations) in the assessment scan
             echo "EXIT_FLAG='critical'" >> env.list 
             echo $LW_ACCOUNT
             docker run --env-file env.list -v "$(pwd):/app/src" lacework/codesec-iac:latest