name: lacework-iac-scan
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Lacework IaC Scan
        env:
          LW_ACCOUNT: ${{ secrets.LW_ACCOUNT }}
          LW_API_KEY: ${{ secrets.API_KEY }}
          LW_API_SECRET: ${{ secrets.API_SECRET_TOKEN }}
        run: |
             env | grep "GITHUB_\|LW_\|CI_" > env.list
             echo "SCAN_COMMAND=tf-scan" >> env.list
             echo "WORKSPACE=src" >> env.list
             echo "EXIT_FLAG='critical'" >> env.list 
             echo $LW_ACCOUNT
             # cat env.list 
             docker run --env-file env.list -v "$(pwd):/app/src" lacework/codesec-iac:latest
      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
             terraform init
             terraform plan
      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
             terraform apply --auto-approve
