name: lacework-iac-scan
on:
  pull_request:
  workflow_dispatch:
permissions:
      id-token: write
      contents: read 
      pull-requests: write   
jobs:
  Lacework-Scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Lacework IaC Scan
        id: laceworkscan
        env:
          LW_ACCOUNT: ${{ secrets.LW_ACCOUNT }}
          LW_API_KEY: ${{ secrets.API_KEY }}
          LW_API_SECRET: ${{ secrets.API_SECRET_TOKEN }}
        run: |
             # Setup 
             IAC_REPORTS_DIR="/tmp/iac_reports"
             env | grep "GITHUB_\|LW_\|CI_" > env.list    # Set Lacework and other secrets
             echo "SCAN_COMMAND=tf-scan" >> env.list      # Configure the scanner to run Terraform Scan
             echo "WORKSPACE=src" >> env.list             
             echo "EXIT_FLAG=critical" >> env.list      # Cause the pipline to fail if any Critical Vulnerbailities are discovered
             echo "JUNIT_OUTPUT_FILE=/tmp/lacework-report.junit.xml"  >> env.list
             echo "JSON_OUTPUT_FILE=/tmp/lacework-report.json"  >> env.list
             
             # Run the Scan
             docker run --env-file env.list -v "$(pwd):/app/src" lacework/codesec-iac:latest
             
             # Copy the report outside lacework/codesec-iac:latest container
             CONTAINER_ID=$(docker ps -a |grep lacework |head -n1 |cut -d ' ' -f1) # Extracts the latest container ID (Inside a pipeline there should be only one anyways)
             mkdir $IAC_REPORTS_DIR
             docker container cp "$CONTAINER_ID:/tmp/lacework-report.json" $IAC_REPORTS_DIR
             docker container cp "$CONTAINER_ID:/tmp/lacework-report.junit.xml" $IAC_REPORTS_DIR
             
             # Set output
             cat $IAC_REPORTS_DIR/lacework-report.json |jq -r '.[].findings | .[].severity'
            # > findings_summary.txt
            #  cat findings_summary.txt
            #  echo "iac_output=$(cat findings_summary.txt)" >> $GITHUB_OUTPUT

      # - name: 'Upload Artifacts'
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Lacework Junit Report
      #     path: /tmp/iac_reports/*

      - name: Update Pull Request
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = "${{ steps.laceworkscan.outputs.iac_output }}"

            github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
            })            

      # - name: Publish Lacework Junit Report
      #   uses: mikepenz/action-junit-report@v4
      #   with:
      #     report_paths: '/tmp/iac_reports/lacework-report.junit.xml'        